from typing import Any

import os
import sys
import tkinter as tk

# Ensure `src` directory is on sys.path so imports like `security` work
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from security.state import StateMemory
from sim.players import Players
from sim.game import Game
from sim.client import Client


memory = StateMemory()


def startGame(
        config: dict[str, Any], state: dict[str, Any],
        istate: dict[str, Any]
        ) -> None:

    # Create the main controller window (for input)
    root = tk.Tk()
    root.title("Game Simulation - Server Controller")

    # Create a Game instance with the initial state and configuration (server view)
    game = Game(istate=istate, config=config, create_ui=True)

    # generate obstacles once on server and expose them to shared state
    game.draw_random_obstacles()
    state['obstacles'] = game.obstaculos
    # precompute rays for all players so server draws rays immediately
    for pid, pos in state.get('positions', {}).items():
        try:
            game.compute_lines_of_sight(pid, pos)
        except Exception:
            pass

    # Create a Player controller
    player = Players()

    # Create a client instance (separate view) that will update StateMemory based on FOV
    client = Client(
        client_id="player1",
        shared_state=state,
        memory=memory,
        fov_deg=90.0,
        radius=8.0,
        dir_angle=0.0,
        cell_size=config.get("tamanho_celula", 50),
        window_size=(600, 600),
        fps=config.get("client_fps", 60),
    )

    # Bind keyboard events to move the players (affects shared state)
    root.bind('<KeyPress>', lambda event: (player.move_using_keyboard(event, state, state['map_width'], state['map_height'])))

    # Initial draw on server
    game.draw(state)

    # Periodic redraw to keep server view in sync (target server_fps)
    server_fps = config.get("server_fps", 60)
    server_interval = int(max(1, 1000 / server_fps))

    def tick():
        try:
            # Server computes visibility and pushes info to StateMemory
            game.update_visibility(state, "player1", memory, fov_deg=90.0, radius=8.0, dir_angle=0.0)
            game.draw(state)
        except Exception:
            pass
        # schedule next tick aiming for server_fps
        root.after(server_interval, tick)

    root.after(200, tick)

    # Start the Tkinter main loop (controller window)
    root.mainloop()


if __name__ == "__main__":
    # Quick test runner: normal-size map and random spawns avoiding obstacles
    import random

    map_w = 20
    map_h = 20
    cell = 50
    cfg = {"largura": map_w * cell, "altura": map_h * cell, "tamanho_celula": cell, "n_rays": 180}

    # create initial empty state; obstacles will be generated by the server
    state = {"map_width": map_w, "map_height": map_h, "positions": {}}
    istate = {}

    # create game to generate obstacles and then pick spawn points
    game = Game(istate=istate, config=cfg, create_ui=False)
    game.draw_random_obstacles()
    obstacles = game.obstaculos

    def cell_blocked_by_obstacles(x: int, y: int) -> bool:
        for obs in obstacles:
            ox, oy, ow, oh, *_ = obs
            if ox <= x <= ox + ow - 1 and oy <= y <= oy + oh - 1:
                return True
        return False

    def find_free_cell(occupied: set[tuple[int, int]], max_tries: int = 1000):
        for _ in range(max_tries):
            x = random.randint(0, map_w - 1)
            y = random.randint(0, map_h - 1)
            if (x, y) in occupied:
                continue
            if cell_blocked_by_obstacles(x, y):
                continue
            return x, y
        # fallback: scan grid
        for iy in range(map_h):
            for ix in range(map_w):
                if (ix, iy) in occupied:
                    continue
                if cell_blocked_by_obstacles(ix, iy):
                    continue
                return ix, iy
        raise RuntimeError("No free cell available")

    occupied: set[tuple[int, int]] = set()

    # spawn client player
    px, py = find_free_cell(occupied)
    occupied.add((px, py))
    state["positions"]["player1"] = (px, py, 0)

    # spawn multiple enemies
    num_enemies = 4
    for i in range(1, num_enemies + 1):
        ex, ey = find_free_cell(occupied)
        occupied.add((ex, ey))
        state["positions"][f"enemy{i}"] = (ex, ey, 0)

    # expose obstacles to state
    state["obstacles"] = obstacles

    startGame(cfg, state, istate)